# Common Application Configurations
spring.profiles.active=prod
server.port=8080

# WebSocket Max Text Message Buffer Size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Configuration
# A 256-bit secure secret key for HMAC-SHA256
journeylink.jwt.secret=4zR9tW8qP2mX6vC1yB5nJ0kH7gF3sA8dE2wQ1uI5oK9lM3vN4bV6cX8zP0aS1dF2g
# Expiration: 1 day in milliseconds (24 hours * 60 mins * 60 secs * 1000)
journeylink.jwt.expiration=86400000
